### ISSUE TITLE
Create architecture graphic

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/meta#13]
#### Description

We need a graphic that lays out and describes the technical architecture of the TV Kitchen ecosystem and vision, essentially a prettier (and updated) version of [this architecture doc](https://github.com/tvkitchen/tv-kitchen/blob/master/docs/img/tv-kitchen.png) for the slightly more casual audience (newsletter subscribers, etc.).

**Comment by slifty** [comment]
This did get done, of course the architecture graphic it resulted in is now out of date too :D

![image](https://user-images.githubusercontent.com/208884/94369424-9bedcc00-00b7-11eb-9222-613fc9d8dfd7.png)
