### ISSUE TITLE
Create `tvkitchen/.github` repo

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/meta#3]
As noted by @chriszs [here](https://github.com/tvkitchen/meta/issues/1#issuecomment-641011120), we should have a `tvkitchen/.github` repo for our "community health files" as [GitHub somewhat tortuously calls them](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file).

Once in place, I think we should consider deleting those files from individual repos (except where truly exceptional). Opened _that_ task as #4.

**Comment by chriszs** [comment]
Just for example, there's no bug report template in the `tv-kitchen` repo, but there is in other repos. Sync issues like that should be taken care of this way.

**Comment by slifty** [comment]
Created!  (I mean, created in the sense that time is not linear)

**Comment by slifty** [comment]
How come this isn't linking the stuff properly :(

**Comment by reefdog** [comment]
@slifty Which stuff and where? It's at least working _sometimes_. For example, on [this very repo](https://github.com/tvkitchen/meta/community), where the Contributing and Pull Request Template links point to the `.github` versions, LICENSE/README are (correctly) local. It looks like the COC and Issue Templates aren't, though?

**Comment by slifty** [comment]
~Huh, when I clicked "create new issue" it didn't seem to pull from the templates!  Must have just been a propagation error.~

Ah yeah that's it -- it's just the issue templates that aren't linking.

So I update to: how come THAT isn't linking properly :(

**Comment by reefdog** [comment]
Issue Templates and COC

**Comment by chriszs** [comment]
> Issue templates and their configuration file must be in a folder called .github/ISSUE_TEMPLATE. All other supported files must be in the root of the repository.

Will fix.

**Comment by chriszs** [comment]
Fixed.

**Comment by slifty** [comment]
Yay! I think we can close this up now, right?  Feel free to re-open if I'm mistaken.
